version: "3"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
    - ./:/app

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
    - ./:/app
    ports:
    - 80:80

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
    - 3306:3306
